### ISSUE TITLE
Application crashes...

### ISSUE THREAD

**Issue by SHROOMKINGonDMT** [MyLegGuy/MangaDownloader-Vita#1]
so basically, downloading chapter 256 of dragon ball from mangareader.net will crash the app. and downloading any chapter after 256 will just start downloading chapter 1,2,3 etc. (happens every time/reproducible)

the chapters are present on the actual website, but they aren't downloadable with this.

anyway, thank you for this awesome app, it's probably my favorite homebrew for vita.

any chance you can provide a compiled version of the latest commit? i tried to compile it myself, but apparently i'm missing lua.h (i'm not, other applications that include lua.h work just fine)  
i really have no clue why i get that compile error.

cheers!

**Comment by MyLegGuy** [comment]
First off, thank you for the bug report. It means a lot to me to know that somebody is actually using this and likes it.

My code expects lua.h to be in a directory called "Lua".
So, it should be <header file folder root>/Lua/lua.h
For me, it's /usr/local/vitasdk/arm-vita-eabi/include/Lua/lua.h
You can either move the header files, or modify Downloader.h.
```
// You would  just change these to be like this: #include <lua.h>
#include <Lua/lua.h>
#include <Lua/lualib.h>
#include <Lua/lauxlib.h>
```
Right now, I'm writing more detailed instructions on compiling. They should be ready soon.

I've released a new version, v2.0. I think it will fix your problem. It also adds some new features, read its notes for more information.

**Comment by SHROOMKINGonDMT** [comment]
Thank you so much! the crash is fixed, and it downloads the right chapters now as well.
I'm gonna report back in case i find any other bug's. 

Maybe someone should make a thread about this on *that vita sub*, since not many people know this exists.

> My code expects lua.h to be in a directory called "Lua".
So, it should be <header file folder root>/Lua/lua.h
For me, it's /usr/local/vitasdk/arm-vita-eabi/include/Lua/lua.h

Ah, well that makes sense, i placed the lua headers into /usr/local/vitasdk/arm-vita-eabi/include/Lua/ and now the include error is gone, thanks again! however now i get the error:

> /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/7.2.0/../../../../arm-vita-eabi/bin/ld.exe: cannot find -llua
collect2.exe: error: ld returned 1 exit status

i've been getting a similar error when the vitasdk autobuilds were missing files. do you know which vitasdk autobuild version you're using?

**Comment by MyLegGuy** [comment]
Yeah, I might make a thread on VitaPiracy subreddit.

Are you sure you've compiled a PS Vita homebrew that requires Lua before?
That error simply means that it can't find the actual compiled Lua library. The way I have it, it should be named "liblua.a"

I'll walk you though compiling Lua.
Step 1 - Download it. https://www.lua.org/ftp/lua-5.3.4.tar.gz
Step 2 - Extract it.
Step 3 - Open the lua-5.3.4 folder and then the src folder.
Step 4 - Find the file called "Makefile". Make sure it's the one in the src directory!
Step 5 - Open it in a text editor.
Step 6 - Find the line that says `CC= gcc -std=gnu99`
Step 7 - Change that line to `CC = arm-vita-eabi-gcc`
Step 8 - Run `make generic` in the src directory.
Step 9 - If it built successfully, you can find a file called liblua.a in the src directory.
Step 10 - Move it to /usr/local/vitasdk/arm-vita-eabi/lib/liblua.a
Step 11 - (Optional) If the compiler still can't find Lua, run `chmod 755 /usr/local/vitasdk/arm-vita-eabi/lib/liblua.a`

Or, you could just download this liblua.a that I compiled and put it in the right spot.
https://www.dropbox.com/s/xkhul7jhfc6fkvq/liblua.a?dl=1

**Comment by SHROOMKINGonDMT** [comment]
haven't used lua with vita homebrew at all.(yet)

i was missing step 7 + i never copied liblua into the vitasdk dir. 
(just did both and now it's working)

thanks for taking the time to help me out, i really appreciate it!

**Comment by MyLegGuy** [comment]
Nice.
