### ISSUE TITLE
Add key repeat on D-pad

### ISSUE THREAD

**Issue by Djhg2000** [MyLegGuy/MangaDownloader-Vita#6]
When browsing in a list you have to keep pressing the up or down arrows to scroll. With key repeat you could just hold one of them to quickly scroll through the list. Optionally also using the L/R shoulder buttons as page up/down would make it faster to browse long lists.

**Comment by MyLegGuy** [comment]
I think this is a pretty good idea, I'll probably add it.

Just so you know, because it sounds like you don't, you can press left and right on the dpad to jump 10 entries. You're also able to search lists, so you shouldn't really need to navigate long ones unless you're just browsing.

**Comment by Djhg2000** [comment]
@MyLegGuy I thought I tried every button but apparently I didn't, the left and right D-pad does indeed jump 10 entries.
