### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by VitaBix** [MyLegGuy/MangaDownloader-Vita#9]
I don't know what to do here please help.

**Comment by MyLegGuy** [comment]
Did you compile the code yourself or just download the [precompiled vpk](https://github.com/MyLegGuy/MangaDownloader-Vita/releases)?

**Comment by VitaBix** [comment]
I downloaded the precompiled version **but for some reason it's now working?.**
Might want to look into it anyways ;)

**Comment by VitaBix** [comment]
You can close this by the way

**Comment by VitaBix** [comment]
Oh well, first time using github
